version: '3.8'
services:
  marketplace-api:
    container_name: marketplace-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - thefishnetwork
        
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: fish_db
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - thefishnetwork

volumes:
  postgres:
    name: nest-db

networks:
  thefishnetwork:
    driver: bridge
    external: true